import type {
  components,
  JournalEntryV2,
  operations,
} from '@restate/data-access/admin-api-spec'; // generated by openapi-typescript
import {
  keepPreviousData,
  MutationOptions,
  Query,
  useMutation,
  useQueries,
  useQuery,
  UseQueryOptions,
  useQueryClient,
  UseQueryResult,
} from '@tanstack/react-query';
import {
  adminApi,
  OperationParameters,
  getOverviewRefreshMeta,
  getDecodeServiceSerdeQueryOptions,
  getEncodeServiceSerdeQueryOptions,
} from '@restate/data-access/admin-api';
import { useAdminBaseUrl } from '@restate/data-access/admin-api';
import type {
  DeploymentId,
  Revision,
  ServiceName,
  Deployment,
  FilterItem,
  Service,
} from '@restate/data-access/admin-api-spec';
import type {
  HookQueryOptions,
  HookMutationOptions,
} from '@restate/data-access/admin-api';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { experimental_createQueryPersister } from '@tanstack/react-query-persist-client';
import { RestateError } from '@restate/util/errors';
import { useAPIStatus } from '@restate/data-access/admin-api';
import { useRange, useRestateContext } from '@restate/features/restate-context';
import { base64ToUint8Array } from '@restate/util/binary';

const SERVICE_TIMESTAMP = new Map<string, Date>();
const unsupportedMetricsBaseUrls = new Set<string>();

function getErrorMessages(error: unknown): string[] {
  if (!(error instanceof Error)) return [];
  return [error.message, ...(error.cause ? getErrorMessages(error.cause) : [])];
}

function isMetricsUnsupportedError(error: unknown) {
  return getErrorMessages(error).some(
    (message) =>
      /table .*metrics_(processor|node|log).* not found/i.test(message) ||
      /metrics_(processor|node|log).* not found/i.test(message),
  );
}

function useMeasuredQueryFn<Args extends unknown[], Result>(
  queryFn: (...args: Args) => Result | Promise<Result>,
  onFetchDuration?: (duration: number) => void,
) {
  return useCallback(
    async (...args: Args) => {
      const startedAt = Date.now();
      try {
        return await queryFn(...args);
      } finally {
        onFetchDuration?.(Date.now() - startedAt);
      }
    },
    [queryFn, onFetchDuration],
  );
}

type ListDeploymentsServiceData = {
  deployments: Record<Revision, DeploymentId[]>;
  sortedRevisions: number[];
  revisionsSet: Set<number>;
};

export type ListDeploymentsData =
  | {
      services: Map<ServiceName, ListDeploymentsServiceData>;
      deployments: Map<DeploymentId, Deployment>;
      sortedServiceNames: ServiceName[];
    }
  | undefined;

export type ListDeploymentsOptions = Omit<
  UseQueryOptions<ListDeploymentsData, RestateError | Error>,
  'queryFn' | 'queryKey'
>;

type ListDeploymentsQueryOptions = UseQueryOptions<
  ListDeploymentsData,
  RestateError | Error
> & {
  queryKey: NonNullable<
    UseQueryOptions<ListDeploymentsData, RestateError | Error>['queryKey']
  >;
};

function listDeploymentsSelector(
  data:
    | {
        deployments: components['schemas']['DeploymentResponse'][];
      }
    | undefined,
): ListDeploymentsData {
  if (!data) {
    return undefined;
  }

  const { deployments: deploymentsFromApi } = data;

  const services = new Map<ServiceName, ListDeploymentsServiceData>();
  const deployments = new Map<DeploymentId, Deployment>();

  for (const deployment of deploymentsFromApi) {
    deployments.set(deployment.id, deployment);

    for (const service of deployment.services) {
      let serviceData = services.get(service.name);

      if (!serviceData) {
        serviceData = {
          deployments: {},
          sortedRevisions: [],
          revisionsSet: new Set<number>(),
        };
        services.set(service.name, serviceData);
      }

      serviceData.revisionsSet.add(service.revision);

      if (!serviceData.deployments[service.revision]) {
        serviceData.deployments[service.revision] = [];
      }
      serviceData.deployments[service.revision]?.push(deployment.id);
    }
  }

  for (const [serviceName, serviceData] of services) {
    serviceData.sortedRevisions = Array.from(serviceData.revisionsSet).sort(
      (a, b) => b - a,
    );

    if (!SERVICE_TIMESTAMP.has(serviceName)) {
      const latestRevision = serviceData.sortedRevisions[0];
      const deploymentId = latestRevision
        ? serviceData.deployments[latestRevision]?.[0]
        : undefined;
      const deployment = deploymentId
        ? deployments.get(deploymentId)
        : undefined;
      const timestamp = deployment?.created_at || Date.now();
      SERVICE_TIMESTAMP.set(serviceName, new Date(timestamp));
    }
  }

  const sortedServiceNames = Array.from(services.keys()).sort((a, b) => {
    const bTimestamp = SERVICE_TIMESTAMP.get(b);
    const aTimestamp = SERVICE_TIMESTAMP.get(a);
    if (!aTimestamp || !bTimestamp) {
      return a.localeCompare(b);
    }
    return bTimestamp.getTime() - aTimestamp.getTime() || a.localeCompare(b);
  });

  return { services, deployments, sortedServiceNames };
}
function listDrainedDeploymentsSelector(
  data:
    | {
        deployment_ids?: string[];
      }
    | undefined,
) {
  return new Set(data?.deployment_ids ?? []);
}

export function getListDeploymentsQueryOptions(
  baseUrl: string,
  options?: ListDeploymentsOptions,
): ListDeploymentsQueryOptions {
  const { queryFn, ...queryOptions } = adminApi(
    'query',
    '/deployments',
    'get',
    {
      baseUrl,
    },
  );

  return {
    ...queryOptions,
    ...options,
    meta: { ...queryOptions.meta, ...getOverviewRefreshMeta() },
    queryFn: (...args: Parameters<typeof queryFn>) =>
      Promise.resolve(queryFn(...args)).then(listDeploymentsSelector),
  };
}

export function useListDeployments(options?: ListDeploymentsOptions) {
  const apiEnabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = getListDeploymentsQueryOptions(baseUrl, options);

  const results = useQuery<ListDeploymentsData>({
    ...queryOptions,
    enabled: queryOptions.enabled !== false && apiEnabled,
  });

  return {
    ...results,
    queryKey: queryOptions.queryKey,
    isPending: results.isPending || !apiEnabled,
  };
}

export function useSqlQuery(
  query: string,
  options?: HookQueryOptions<'/query', 'post'>,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = adminApi('query', '/query', 'post', {
    baseUrl,
    body: { query },
  });

  const results = useQuery({
    ...queryOptions,
    ...options,
    enabled: Boolean(query) && options?.enabled !== false && enabled,
  });

  return {
    ...results,
    queryKey: queryOptions.queryKey,
  };
}

export function useListDrainedDeployments(
  options?: HookQueryOptions<'/query/deployments/drained', 'get'>,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = adminApi('query', '/query/deployments/drained', 'get', {
    baseUrl,
  });

  const results = useQuery({
    ...queryOptions,
    ...options,
    meta: { ...queryOptions.meta, ...getOverviewRefreshMeta() },
    select: listDrainedDeploymentsSelector,
    enabled: options?.enabled !== false && enabled,
  });

  return {
    ...results,
    queryKey: queryOptions.queryKey,
  };
}

export function useGetMetrics(
  options?: HookQueryOptions<'/query/metrics', 'get'>,
) {
  const enabled = useAPIStatus();
  const { isExecutionMetricsEnabled } = useRestateContext();
  const baseUrl = useAdminBaseUrl();
  const [isMetricsUnsupported, setIsMetricsUnsupported] = useState(() =>
    unsupportedMetricsBaseUrls.has(baseUrl),
  );
  const isMetricsEnabled =
    isExecutionMetricsEnabled &&
    options?.enabled !== false &&
    !isMetricsUnsupported;
  const queryOptions = adminApi('query', '/query/metrics', 'get', {
    baseUrl,
  });

  const results = useQuery({
    refetchInterval: 2_000,
    ...queryOptions,
    ...options,
    meta: { ...queryOptions.meta, ...getOverviewRefreshMeta() },
    enabled: enabled && isMetricsEnabled,
  });

  useEffect(() => {
    setIsMetricsUnsupported(unsupportedMetricsBaseUrls.has(baseUrl));
  }, [baseUrl]);

  useEffect(() => {
    if (!results.error || isMetricsUnsupported) return;
    if (isMetricsUnsupportedError(results.error)) {
      unsupportedMetricsBaseUrls.add(baseUrl);
      setIsMetricsUnsupported(true);
    }
  }, [baseUrl, isMetricsUnsupported, results.error]);

  const hasLoadedMetrics = isMetricsEnabled && results.dataUpdatedAt > 0;

  return {
    ...results,
    data: isMetricsEnabled ? results.data : undefined,
    hasLoadedMetrics,
    isMetricsEnabled,
    isMetricsUnsupported,
    queryKey: queryOptions.queryKey,
  };
}

export function isVersionQuery(
  data: unknown,
  query: Query<unknown, unknown, unknown>,
): data is components['schemas']['VersionInformation'] {
  const { queryKey } = query;
  return Array.isArray(queryKey) && queryKey[0] === '/version';
}

export function isListDeployments(
  data: unknown,
  query: Query<unknown, unknown, unknown>,
): data is NonNullable<ListDeploymentsData> {
  const { queryKey, meta } = query;
  return (
    Array.isArray(queryKey) &&
    queryKey[0] === '/deployments' &&
    meta?.['method'] === 'get'
  );
}

export function isListInvocations(
  data: unknown,
  query: Query<unknown, Error, unknown, readonly unknown[]>,
): data is operations['list_invocations']['responses']['200']['content']['application/json'] {
  const { queryKey, meta } = query;
  return (
    Array.isArray(queryKey) &&
    queryKey[0] === '/query/invocations' &&
    meta?.['method'] === 'post'
  );
}

export function isGetInvocationJournalWithInvocationV2(
  data: unknown,
  query: Query<unknown, unknown, unknown>,
): data is operations['get_invocation_journal_v2']['responses']['200']['content']['application/json'] {
  const { queryKey, meta } = query;
  return (
    Array.isArray(queryKey) &&
    queryKey[0] === '/query/v2/invocations/{invocationId}' &&
    meta?.['method'] === 'get'
  );
}

export function useRegisterDeployment(
  options?: Omit<
    HookMutationOptions<'/deployments', 'post'>,
    'mutationFn' | 'mutationKey' | 'onSettled'
  > & { retryWithHttp1?: boolean },
) {
  const baseUrl = useAdminBaseUrl();
  const { onSuccess, retryWithHttp1, ...rest } = options ?? {};
  const queryCLient = useQueryClient();
  const mutationOptions = adminApi('mutate', '/deployments', 'post', {
    baseUrl,
  });

  const { mutationFn: _mutationFn, meta } = mutationOptions;
  const mutationFn: typeof mutationOptions.mutationFn = useCallback(
    async (args, context) => {
      return _mutationFn(args, context).catch(async (originalError) => {
        if (
          retryWithHttp1 &&
          args.body &&
          args.body.dry_run &&
          'uri' in args.body
        ) {
          try {
            await _mutationFn(
              {
                ...args,
                body: {
                  ...args.body,
                  use_http_11: true,
                },
              },
              { client: queryCLient, meta },
            );
            throw new RestateError(
              'Service discovery response failed, and the server may have responded in HTTP1.1.',
              'META0014',
            );
          } catch (_) {
            throw originalError;
          }
        }
        throw originalError;
      });
    },
    [_mutationFn, meta, queryCLient, retryWithHttp1],
  );

  return useMutation({
    ...mutationOptions,
    ...rest,
    mutationFn,
    onSuccess(data, variables, context, meta) {
      if (!variables.body?.dry_run) {
        data?.services.forEach((service) => {
          const serviceName = service.name;
          const { queryKey } = getServiceAdminApi({
            baseUrl,
            parameters: { path: { service: serviceName } },
          });
          queryCLient.invalidateQueries({
            queryKey,
          });
        });
      }
      return onSuccess?.(data, variables, context, meta);
    },
  });
}

export function useUpdateDeployment(
  deployment: string,
  options?: Omit<
    HookMutationOptions<'/deployments/{deployment}', 'patch'>,
    'mutationFn' | 'mutationKey' | 'onSettled'
  > & { retryWithHttp1?: boolean },
) {
  const baseUrl = useAdminBaseUrl();
  const { onSuccess, retryWithHttp1, ...rest } = options ?? {};
  const queryCLient = useQueryClient();
  const mutationOptions = adminApi(
    'mutate',
    '/deployments/{deployment}',
    'patch',
    {
      baseUrl,
      resolvedPath: `/deployments/${deployment}`,
    },
  );

  const { mutationFn: _mutationFn, meta } = mutationOptions;
  const mutationFn: typeof mutationOptions.mutationFn = useCallback(
    async (args, context) => {
      return _mutationFn(
        {
          ...args,
          parameters: {
            path: {
              deployment,
            },
          },
        },
        context,
      ).catch(async (originalError) => {
        if (
          retryWithHttp1 &&
          args.body &&
          args.body.dry_run &&
          'uri' in args.body
        ) {
          try {
            await _mutationFn(
              {
                ...args,
                parameters: {
                  path: {
                    deployment,
                  },
                },
                body: {
                  ...args.body,
                  use_http_11: true,
                },
              },
              { client: queryCLient, meta },
            );
            throw new RestateError(
              'Service discovery response failed, and the server may have responded in HTTP1.1.',
              'META0014',
            );
          } catch (_) {
            throw originalError;
          }
        }
        throw originalError;
      });
    },
    [_mutationFn, meta, queryCLient, retryWithHttp1, deployment],
  );

  return useMutation({
    ...mutationOptions,
    ...rest,
    mutationFn,
    onSuccess(data, variables, context, meta) {
      if (!variables.body?.dry_run) {
        data?.services.forEach((service) => {
          const serviceName = service.name;
          const { queryKey } = getServiceAdminApi({
            baseUrl,
            parameters: { path: { service: serviceName } },
          });
          queryCLient.invalidateQueries({
            queryKey,
          });
        });
        queryCLient.invalidateQueries({
          queryKey: adminApi('query', '/deployments', 'get', { baseUrl })
            .queryKey,
        });
        queryCLient.invalidateQueries({
          queryKey: adminApi('query', '/deployments/{deployment}', 'get', {
            baseUrl,
            resolvedPath: `/deployments/${deployment}`,
            parameters: { path: { deployment } },
          }).queryKey,
        });
      }
      return onSuccess?.(data, variables, context, meta);
    },
  });
}

function getServiceAdminApi(init: {
  baseUrl: string;
  parameters?: OperationParameters<'/services/{service}', 'get'>;
  resolvedPath?: string;
}) {
  const { queryFn, ...queryOptions } = adminApi(
    'query',
    '/services/{service}',
    'get',
    init,
  );

  return {
    ...queryOptions,
    queryFn: (...args: Parameters<typeof queryFn>) =>
      Promise.resolve(queryFn(...args))?.then((data) => {
        if (!data) {
          return data;
        }
        return {
          ...data,
          handlers: data?.handlers.sort((a, b) => a.name.localeCompare(b.name)),
        };
      }),
  };
}

export function useServiceDetails(
  service: string,
  options?: HookQueryOptions<'/services/{service}', 'get'>,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const { queryFn, ...queryOptions } = getServiceAdminApi({
    baseUrl,
    parameters: { path: { service } },
  });

  const results = useQuery({
    staleTime: 0,
    ...queryOptions,
    queryFn: (...args: Parameters<typeof queryFn>) =>
      Promise.resolve(queryFn(...args))?.then((data) => {
        if (!data) {
          return data;
        }
        return {
          ...data,
          handlers: data?.handlers.sort((a, b) => a.name.localeCompare(b.name)),
        };
      }),
    ...options,
    meta: { ...queryOptions.meta, ...getOverviewRefreshMeta() },
    enabled: options?.enabled !== false && enabled,
  });

  return { ...results, queryKey: queryOptions.queryKey };
}

export function useListServices(
  services: string[] = [],
  options?: HookQueryOptions<'/services/{service}', 'get'>,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();

  const results = useQueries({
    queries: services.map((service) => ({
      ...getServiceAdminApi({
        baseUrl,
        parameters: { path: { service } },
      }),
      staleTime: 0,
      ...options,
      enabled: options?.enabled !== false && enabled,
    })),
    combine: (results) => {
      return {
        data: results.reduce((result, service) => {
          if (service.data) {
            result.set(service.data?.name, service.data);
          }
          return result;
        }, new Map<string, Service>()),
        isPending: results.some((result) => result.isPending) || !enabled,
        promise: Promise.all(results.map(({ promise }) => promise)),
      };
    },
  });

  return results;
}

export function useDeploymentDetails(
  deployment: string,
  options?: HookQueryOptions<'/deployments/{deployment}', 'get'>,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = adminApi('query', '/deployments/{deployment}', 'get', {
    baseUrl,
    resolvedPath: `/deployments/${deployment}`,
    parameters: { path: { deployment } },
  });

  const results = useQuery({
    staleTime: 0,
    ...queryOptions,
    ...options,
    enabled: options?.enabled !== false && enabled,
  });

  return { ...results, queryKey: queryOptions.queryKey };
}

export function useListSubscriptions(
  options?: HookQueryOptions<'/subscriptions', 'get'>,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = adminApi('query', '/subscriptions', 'get', {
    baseUrl,
  });

  const results = useQuery({
    staleTime: 0,
    ...queryOptions,
    ...options,
    enabled: options?.enabled !== false && enabled,
  });

  return { ...results, queryKey: queryOptions.queryKey };
}

export function useCountInvocations(
  filters: FilterItem[],
  options?: HookQueryOptions<'/query/invocations/count', 'post'>,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = adminApi('query', '/query/invocations/count', 'post', {
    baseUrl,
    body: {
      filters,
    },
  });

  const results = useQuery({
    staleTime: 0,
    ...queryOptions,
    ...options,
    enabled: options?.enabled !== false && enabled,
  });

  return { ...results, queryKey: queryOptions.queryKey };
}

export function useSummaryInvocations(
  filters: FilterItem[],
  {
    // Default to non-sampled (exact counts). Server defaults to true otherwise
    // — sampling is a per-call opt-in, not the implicit behavior.
    sampled = false,
    sampleSize,
    range,
    excludeCompleted,
    meta: callerMeta,
    onFetchDuration,
    ...options
  }: HookQueryOptions<'/query/invocations/summary', 'post'> & {
    sampled?: boolean;
    sampleSize?: number;
    range?: string;
    excludeCompleted?: boolean;
    onFetchDuration?: (duration: number) => void;
  } = {},
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const currentRange = useRange();
  const isMonitorQuery = filters.length === 0 && range === currentRange;

  const { queryFn, ...queryOptions } = adminApi(
    'query',
    '/query/invocations/summary',
    'post',
    {
      baseUrl,
      body: {
        filters,
        sampled,
        sampleSize,
        range,
        excludeCompleted,
      },
    },
  );
  const measuredQueryFn = useMeasuredQueryFn(queryFn, onFetchDuration);

  const results = useQuery({
    staleTime: 0,
    placeholderData: keepPreviousData,
    ...queryOptions,
    ...options,
    queryFn: measuredQueryFn,
    meta: {
      ...queryOptions.meta,
      ...getOverviewRefreshMeta(),
      ...callerMeta,
      ...(isMonitorQuery && { monitor: true }),
    },
    enabled: options?.enabled !== false && enabled,
  });

  return { ...results, queryKey: queryOptions.queryKey };
}

export function useCompletedInvocationsBreakdown({
  startTime,
  endTime,
  interval,
  filters = [],
  ...options
}: HookQueryOptions<'/query/invocations/completed-breakdown', 'post'> & {
  startTime: string;
  endTime: string;
  interval: string;
  filters?: FilterItem[];
}) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();

  const queryOptions = adminApi(
    'query',
    '/query/invocations/completed-breakdown',
    'post',
    {
      baseUrl,
      body: {
        startTime,
        endTime,
        interval,
        filters,
      },
    },
  );

  const results = useQuery({
    staleTime: 0,
    placeholderData: keepPreviousData,
    ...queryOptions,
    ...options,
    enabled: options?.enabled !== false && enabled,
  });

  return { ...results, queryKey: queryOptions.queryKey };
}

const HOUR_MS = 60 * 60 * 1000;
const COMPLETED_TIMELINE_BUCKETS = 24;
const COMPLETED_TIMELINE_HISTORY_BUCKETS = COMPLETED_TIMELINE_BUCKETS - 1;
const COMPLETED_BREAKDOWN_PATH = '/query/invocations/completed-breakdown';

type CompletedBreakdownData =
  components['schemas']['CompletedInvocationsBreakdownResponse'];
type CompletedBreakdownBucket = CompletedBreakdownData['buckets'][number];

function floorTo(ms: number, unit: number) {
  return Math.floor(ms / unit) * unit;
}

// Merge bucket lists, deduped by start (later sources win), ordered ascending.
function mergeBuckets(
  ...sources: (readonly CompletedBreakdownBucket[] | undefined)[]
): CompletedBreakdownBucket[] {
  const byStart = new Map<string, CompletedBreakdownBucket>();
  for (const source of sources) {
    for (const bucket of source ?? []) {
      byStart.set(bucket.start, bucket);
    }
  }
  return [...byStart.values()].sort((a, b) =>
    a.start < b.start ? -1 : a.start > b.start ? 1 : 0,
  );
}

const COMPLETED_BREAKDOWN_PREFIX = 'restate-completed-breakdown';

// localStorage-backed persister for the immutable history, with self-cleanup.
// The wrapper adds `entries()` (raw localStorage has none, and persisterGc needs
// it to enumerate) scoped to our prefix, and runs persisterGc on every write —
// so each newly saved snapshot sweeps out the expired ones from past sessions
// instead of letting them pile up. `maxAge` is short because the key rotates
// hourly (a persisted entry is only useful for a same-hour reload), and `buster`
// drops entries when the bucket shape changes. The live query is not persisted.
const completedBreakdownGc: { run?: () => Promise<void> } = {};
const completedBreakdownStorage =
  typeof localStorage === 'undefined'
    ? undefined
    : {
        getItem: (key: string) => localStorage.getItem(key),
        setItem: (key: string, value: string) => {
          localStorage.setItem(key, value);
          void completedBreakdownGc.run?.()?.catch(() => undefined);
        },
        removeItem: (key: string) => localStorage.removeItem(key),
        entries: (): Array<[string, string]> =>
          Object.entries(localStorage).filter(([key]) =>
            key.startsWith(COMPLETED_BREAKDOWN_PREFIX),
          ),
      };
const completedBreakdownPersisterApi = experimental_createQueryPersister({
  storage: completedBreakdownStorage,
  maxAge: 2 * HOUR_MS,
  prefix: COMPLETED_BREAKDOWN_PREFIX,
  buster: 'v1',
});
completedBreakdownGc.run = completedBreakdownPersisterApi.persisterGc;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const completedBreakdownPersister: any =
  completedBreakdownPersisterApi.persisterFn;

/**
 * Hourly succeeded/failed timeline for the last 24 buckets, split at a single
 * `boundary` (the end of history and the start of the live hour):
 *
 *  - `history` — [boundary - 23h, boundary): one immutable scan.
 *    staleTime Infinity + refetchOnMount false + persisted, so it runs once and
 *    is shared across tabs/windows and reloads.
 *  - `live` — [boundary, boundary + 1h): the current partial hour, polled on
 *    `refetchInterval`.
 *
 * On the hour rollover the just-completed hour from the live poll is folded into
 * history and `boundary` advances. The extended history key is *seeded* from the
 * old data + the poll, so the expensive scan is never re-run.
 */
export function useCompletedInvocationsTimeline({
  filters = [],
  refetchInterval = 30_000,
  enabled: callerEnabled,
}: {
  filters?: FilterItem[];
  refetchInterval?: number | (() => number | false);
  enabled?: boolean;
} = {}) {
  const apiEnabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryClient = useQueryClient();
  const enabled = callerEnabled !== false && apiEnabled;
  const interval = 'PT1H';

  // `boundary` is the split point: end of history and start of the live hour.
  // `historyStart` tracks the beginning of the rolling history window.
  const [{ historyStart, boundary }, setSplit] = useState(() => {
    const now = Date.now();
    const boundary = floorTo(now, HOUR_MS);
    return {
      historyStart: boundary - COMPLETED_TIMELINE_HISTORY_BUCKETS * HOUR_MS,
      boundary,
    };
  });
  const historyStartISO = new Date(historyStart).toISOString();
  const boundaryISO = new Date(boundary).toISOString();

  // history — [historyStart, boundary). Fetched once and pinned; on rollover
  // its key changes but we seed the new key (below) so it usually avoids a
  // re-scan.
  const historyApi = adminApi('query', COMPLETED_BREAKDOWN_PATH, 'post', {
    baseUrl,
    body: {
      startTime: historyStartISO,
      endTime: boundaryISO,
      interval,
      filters,
    },
  });
  const history = useQuery({
    ...historyApi,
    staleTime: Infinity,
    refetchOnMount: false,
    placeholderData: keepPreviousData,
    persister: completedBreakdownPersister,
    enabled,
  });

  // live — the current, still-accumulating hour, [boundary, boundary + 1h). The
  // server only counts `completed_at < endTime` and nothing has completed past
  // `now`, so this is just "the current hour so far". Because the window is the
  // whole hour (not `now`), the body is stable per boundary, so polling
  // (refetchInterval) refreshes a single cache entry as completions trickle in —
  // no need to thread `now` through the key. Not persisted; the rollover effect
  // folds it into history once the hour ends.
  const liveApi = adminApi('query', COMPLETED_BREAKDOWN_PATH, 'post', {
    baseUrl,
    body: {
      startTime: boundaryISO,
      endTime: new Date(boundary + HOUR_MS).toISOString(),
      interval,
      filters,
    },
  });
  const live = useQuery({
    ...liveApi,
    staleTime: 0,
    refetchInterval,
    enabled,
  });

  // Rollover: each poll, check whether the wall clock has entered a new hour.
  // On a single-hour step, fold the now-complete hour (from the live poll) into
  // history and seed the extended history key so the expensive scan isn't re-run.
  // A multi-hour jump (e.g. a long-backgrounded tab) can't be backfilled from the
  // single-hour live window, so skip the seed and let history refetch the full
  // range once when the boundary advances.
  const liveUpdatedAt = live.dataUpdatedAt;
  const filtersKey = JSON.stringify(filters);
  useEffect(() => {
    const nextBoundary = floorTo(Date.now(), HOUR_MS);
    // Not a new hour yet, or the latest poll predates the boundary (so it hasn't
    // captured the completed hour) — wait for the next poll.
    if (nextBoundary <= boundary || liveUpdatedAt < nextBoundary) {
      return;
    }
    const previous = queryClient.getQueryData<CompletedBreakdownData>(
      historyApi.queryKey,
    );
    const nextHistoryStart =
      nextBoundary - COMPLETED_TIMELINE_HISTORY_BUCKETS * HOUR_MS;
    const nextHistoryStartISO = new Date(nextHistoryStart).toISOString();
    const nextBoundaryISO = new Date(nextBoundary).toISOString();
    if (previous && nextBoundary === boundary + HOUR_MS) {
      const liveData = queryClient.getQueryData<CompletedBreakdownData>(
        liveApi.queryKey,
      );
      const completed = (liveData?.buckets ?? []).filter(
        (bucket) => bucket.start < nextBoundaryISO,
      );
      const nextHistoryApi = adminApi(
        'query',
        COMPLETED_BREAKDOWN_PATH,
        'post',
        {
          baseUrl,
          body: {
            startTime: nextHistoryStartISO,
            endTime: nextBoundaryISO,
            interval,
            filters,
          },
        },
      );
      queryClient.setQueryData<CompletedBreakdownData>(
        nextHistoryApi.queryKey,
        {
          startTime: nextHistoryStartISO,
          endTime: nextBoundaryISO,
          interval,
          buckets: mergeBuckets(previous.buckets, completed).filter(
            (bucket) =>
              bucket.start >= nextHistoryStartISO &&
              bucket.start < nextBoundaryISO,
          ),
        },
      );
    }
    setSplit({ historyStart: nextHistoryStart, boundary: nextBoundary });
    // history/live keys, `filters` and `interval` are all derived from the
    // primitives below; the tick that drives this is `liveUpdatedAt`.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    liveUpdatedAt,
    boundary,
    baseUrl,
    historyStartISO,
    filtersKey,
    queryClient,
  ]);

  // Only ever surface buckets up to the end of the current hour: clamp the live
  // source so a bucket beyond the live window can't leak in (today `live` is
  // keyed to [boundary, boundary + 1h) so this is just the one current-hour
  // bucket, but the clamp keeps the result correct regardless).
  const historyBuckets = history.data?.buckets;
  const liveData = live.data;
  const buckets = useMemo(() => {
    const hourEndISO = new Date(boundary + HOUR_MS).toISOString();
    const liveBuckets = (liveData?.buckets ?? []).filter(
      (bucket) => bucket.start < hourEndISO,
    );
    return mergeBuckets(historyBuckets, liveBuckets);
  }, [historyBuckets, liveData, boundary]);

  return {
    buckets,
    // The expensive history gates the first render; the live tail fills in
    // without blocking.
    isPending: history.isPending,
    isLoading: history.isLoading,
    isFetching: history.isFetching || live.isFetching,
    isError: history.isError || live.isError,
    error: history.error ?? live.error ?? null,
    history,
    live,
  };
}

function isCompletedInvocationStatus(
  status?: components['schemas']['InvocationStatus'],
) {
  return status === 'succeeded' || status === 'failed';
}

type InvocationStatusDetails = components['schemas']['InvocationStatusResult'];

type InvocationStatusDetailsData =
  operations['get_invocations_statuses']['responses']['200']['content']['application/json'];

function getInvocationStatusDetailsQueryKey(
  baseUrl: string,
  referenceInvocationId?: string,
) {
  return [
    '/query/invocations/statuses/latest',
    {
      baseUrl,
      method: 'post' as const,
      referenceInvocationId,
    },
  ] as const;
}

export function useWarmInvocationStatusDetails(
  invocationIds: string[],
  referenceInvocationId?: string,
  options?: HookQueryOptions<'/query/invocations/statuses', 'post'>,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryInvocationIds = [
    ...new Set(invocationIds.filter((invocationId) => invocationId.length > 0)),
  ];
  const latestQueryKey = getInvocationStatusDetailsQueryKey(
    baseUrl,
    referenceInvocationId,
  );
  const queryOptions = adminApi(
    'query',
    '/query/invocations/statuses',
    'post',
    {
      baseUrl,
      parameters: {
        query: {
          referenceInvocationId,
        },
      },
      body: {
        invocationIds: queryInvocationIds,
      },
    },
  );

  const results = useQuery({
    ...queryOptions,
    ...options,
    queryKey: latestQueryKey,
    queryFn: async (context) => {
      const latestData =
        context.client.getQueryData<InvocationStatusDetailsData>(
          latestQueryKey,
        ) ?? {
          invocations: {},
        };
      const cachedInvocations = latestData.invocations;
      const completedInvocations = Object.fromEntries(
        queryInvocationIds.flatMap((invocationId) =>
          isCompletedInvocationStatus(cachedInvocations[invocationId]?.status)
            ? [[invocationId, cachedInvocations[invocationId]]]
            : [],
        ),
      );
      const nonCompletedInvocationIds = queryInvocationIds.filter(
        (invocationId) =>
          !isCompletedInvocationStatus(cachedInvocations[invocationId]?.status),
      );
      const mergedInvocations = {
        ...latestData.invocations,
        ...completedInvocations,
      };

      if (nonCompletedInvocationIds.length === 0) {
        return { invocations: mergedInvocations };
      }

      const fetchedData = (await adminApi(
        'query',
        '/query/invocations/statuses',
        'post',
        {
          baseUrl,
          parameters: {
            query: {
              referenceInvocationId,
            },
          },
          body: {
            invocationIds: nonCompletedInvocationIds,
          },
        },
      ).queryFn(context)) ?? { invocations: {} };
      return {
        invocations: {
          ...mergedInvocations,
          ...fetchedData.invocations,
        },
      };
    },
    enabled: options?.enabled !== false && enabled,
  });

  return {
    ...results,
    queryKey: latestQueryKey,
  };
}

export function useGetInvocationStatusDetails(
  invocationId?: string,
  referenceInvocationId?: string,
) {
  const baseUrl = useAdminBaseUrl();
  const latestQueryKey = getInvocationStatusDetailsQueryKey(
    baseUrl,
    referenceInvocationId,
  );
  const query = useQuery<InvocationStatusDetailsData, RestateError | Error>({
    queryKey: latestQueryKey,
    queryFn: async () => ({ invocations: {} }),
    enabled: false,
  });
  const data = invocationId
    ? query.data?.invocations?.[invocationId]
    : undefined;
  const isCompleted = isCompletedInvocationStatus(data?.status);

  return {
    ...query,
    data: data as InvocationStatusDetails | undefined,
    isPending:
      invocationId && referenceInvocationId
        ? isCompleted
          ? false
          : query.isPending
        : false,
    error:
      invocationId && referenceInvocationId
        ? isCompleted
          ? null
          : query.error
        : null,
  };
}

export function useModifyService(
  service: string,
  options?: HookMutationOptions<'/services/{service}', 'patch'>,
) {
  const baseUrl = useAdminBaseUrl();

  return useMutation({
    ...adminApi('mutate', '/services/{service}', 'patch', {
      baseUrl,
      resolvedPath: `/services/${service}`,
    }),
    ...options,
  });
}

export function useDeleteDeployment(
  deployment: string,
  options?: HookMutationOptions<'/deployments/{deployment}', 'delete'>,
) {
  const baseUrl = useAdminBaseUrl();

  return useMutation({
    ...adminApi('mutate', '/deployments/{deployment}', 'delete', {
      baseUrl,
      resolvedPath: `/deployments/${deployment}`,
    }),
    ...options,
  });
}

export function useServiceOpenApi(
  service: string,
  options?: HookQueryOptions<'/services/{service}/openapi', 'get'>,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = adminApi('query', '/services/{service}/openapi', 'get', {
    baseUrl,
    parameters: { path: { service } },
  });

  const results = useQuery({
    staleTime: 0,
    ...queryOptions,
    ...options,
    enabled: options?.enabled !== false && enabled,
  });

  return { ...results, queryKey: queryOptions.queryKey };
}

type ServiceSerdeName =
  operations['decode_service_serde']['parameters']['path']['serdeName'];

type DecodeServiceSerdeBody = string | Uint8Array;

type DecodeServiceSerdeOptions = HookQueryOptions<
  '/internal/services/{service}/serdes/decode/{serdeName}',
  'post'
> & {
  parameters?: Pick<operations['decode_service_serde']['parameters'], 'query'>;
};

type EncodeServiceSerdeOptions = HookQueryOptions<
  '/internal/services/{service}/serdes/encode/{serdeName}',
  'post',
  Uint8Array
> & {
  parameters?: Pick<operations['encode_service_serde']['parameters'], 'query'>;
};

export function useDecodeServiceSerde(
  service: string,
  serdeName: ServiceSerdeName,
  body?: DecodeServiceSerdeBody,
  { parameters, ...options }: DecodeServiceSerdeOptions = {},
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = getDecodeServiceSerdeQueryOptions(baseUrl, {
    service,
    serdeName,
    body,
    deployment: parameters?.query?.deployment,
  });

  const results = useQuery({
    ...queryOptions,
    ...options,
    enabled: body !== undefined && options.enabled !== false && enabled,
  });

  return { ...results, queryKey: queryOptions.queryKey };
}

export function useEncodeServiceSerde(
  service: string,
  serdeName: ServiceSerdeName,
  body?: operations['encode_service_serde']['requestBody']['content']['application/json'],
  { parameters, ...options }: EncodeServiceSerdeOptions = {},
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = getEncodeServiceSerdeQueryOptions(baseUrl, {
    service,
    serdeName,
    body,
    deployment: parameters?.query?.deployment,
  });

  const results = useQuery({
    ...queryOptions,
    ...options,
    enabled: body !== undefined && options.enabled !== false && enabled,
  });

  return { ...results, queryKey: queryOptions.queryKey };
}

export function useListInvocations(
  body: components['schemas']['ListInvocationsRequestBody'],
  options?: HookQueryOptions<'/query/invocations', 'post'>,
) {
  const enabled = useAPIStatus();

  const baseUrl = useAdminBaseUrl();
  const queryOptions = adminApi('query', '/query/invocations', 'post', {
    baseUrl,
    body: body,
  });

  const results = useQuery({
    ...queryOptions,
    ...options,
    enabled: options?.enabled !== false && enabled,
  });

  return {
    ...results,
    queryKey: queryOptions.queryKey,
    isPending: results.isPending || !enabled,
  };
}

export function useGetInvocation(
  invocationId: string,
  options?: HookQueryOptions<'/query/invocations/{invocationId}', 'get'>,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = adminApi(
    'query',
    '/query/invocations/{invocationId}',
    'get',
    {
      baseUrl,
      parameters: { path: { invocationId } },
    },
  );

  const results = useQuery({
    ...queryOptions,
    ...options,
    enabled: options?.enabled !== false && enabled,
  });

  return {
    ...results,
    queryKey: queryOptions.queryKey,
  };
}

export function useGetPausedError(
  invocationId: string,
  options?: HookQueryOptions<
    '/query/invocations/{invocationId}/paused-error',
    'get'
  >,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = adminApi(
    'query',
    '/query/invocations/{invocationId}/paused-error',
    'get',
    {
      baseUrl,
      parameters: { path: { invocationId } },
    },
  );

  const results = useQuery({
    ...queryOptions,
    ...options,
    enabled: options?.enabled !== false && enabled,
  });

  return {
    ...results,
    queryKey: queryOptions.queryKey,
  };
}

export function useGetTransientError(
  invocationId: string,
  options?: HookQueryOptions<
    '/query/invocations/{invocationId}/transient-error',
    'get'
  >,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = adminApi(
    'query',
    '/query/invocations/{invocationId}/transient-error',
    'get',
    {
      baseUrl,
      parameters: { path: { invocationId } },
    },
  );

  const results = useQuery({
    ...queryOptions,
    ...options,
    enabled: options?.enabled !== false && enabled,
  });

  return {
    ...results,
    queryKey: queryOptions.queryKey,
  };
}

export function useGetInvocationJournalEntry(
  invocationId: string,
  entryIndex: number,
  options?: HookQueryOptions<
    '/query/invocations/{invocationId}/journal/{entryIndex}',
    'get'
  >,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = adminApi(
    'query',
    '/query/invocations/{invocationId}/journal/{entryIndex}',
    'get',
    {
      baseUrl,
      resolvedPath: `/query/invocations/${invocationId}/journal/${entryIndex}`,
      parameters: { path: { invocationId, entryIndex } },
    },
  );

  const results = useQuery({
    ...queryOptions,
    ...options,
    enabled: options?.enabled !== false && enabled,
  });

  return results;
}

export function useGetJournalEntryPayloads(
  invocationId: string,
  entryIndex: number,
  options?: HookQueryOptions<
    '/query/invocations/{invocationId}/journal/{entryIndex}/payloads',
    'get'
  >,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = adminApi(
    'query',
    '/query/invocations/{invocationId}/journal/{entryIndex}/payloads',
    'get',
    {
      baseUrl,
      parameters: { path: { invocationId, entryIndex } },
    },
  );

  return useQuery({
    ...queryOptions,
    ...options,
    enabled: options?.enabled !== false && enabled,
  });
}

export function useGetInvocationJournalWithInvocationV2(
  invocationId: string,
  options?: HookQueryOptions<'/query/v2/invocations/{invocationId}', 'get'>,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const query = adminApi(
    'query',
    '/query/v2/invocations/{invocationId}',
    'get',
    {
      baseUrl,
      parameters: {
        path: { invocationId },
        query: { journal: true, includePayloads: false },
      },
    },
  );
  const results = useQuery({
    ...query,
    ...options,
    enabled: options?.enabled !== false && enabled,
  });

  return { queryKey: query.queryKey, ...results };
}

export function useGetInvocationsJournalWithInvocationsV2(
  invocationIds: string[],
  options?: HookQueryOptions<'/query/v2/invocations/{invocationId}', 'get'>,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const invocationQueries = useMemo(
    () =>
      invocationIds.map((invocationId) =>
        adminApi('query', '/query/v2/invocations/{invocationId}', 'get', {
          baseUrl,
          parameters: {
            path: { invocationId },
            query: { journal: true, includePayloads: false },
          },
        }),
      ),
    [baseUrl, invocationIds],
  );

  const combine = useCallback(
    (
      results: UseQueryResult<
        | ReturnType<typeof useGetInvocationJournalWithInvocationV2>['data']
        | undefined,
        Error
      >[],
    ) => {
      return {
        data: invocationIds.reduce(
          (combined, invocationId, index) => {
            return {
              ...combined,
              [invocationId]: results.at(index)?.data,
            };
          },
          {} as Record<
            string,
            ReturnType<typeof useGetInvocationJournalWithInvocationV2>['data']
          >,
        ),
        isPending: invocationIds.reduce(
          (combined, invocationId, index) => {
            return {
              ...combined,
              [invocationId]: results.at(index)?.isPending,
            };
          },
          {} as Record<string, boolean | undefined>,
        ),
        isSuccess: invocationIds.reduce(
          (combined, invocationId, index) => {
            return {
              ...combined,
              [invocationId]: results.at(index)?.isSuccess,
            };
          },
          {} as Record<string, boolean | undefined>,
        ),
        error: invocationIds.reduce(
          (combined, invocationId, index) => {
            return {
              ...combined,
              [invocationId]: results.at(index)?.error,
            };
          },
          {} as Record<string, Error | null | undefined>,
        ),
        dataUpdatedAt: invocationIds.reduce(
          (combined, invocationId, index) => {
            return {
              ...combined,
              [invocationId]: results.at(index)?.dataUpdatedAt,
            };
          },
          {} as Record<string, number | undefined>,
        ),
      };
    },
    [invocationIds],
  );

  const results = useQueries({
    queries: [
      ...invocationQueries.map((invocationQuery) => ({
        ...invocationQuery,
        ...options,
        refetchOnMount: options?.refetchOnMount !== false,
        enabled: options?.enabled !== false && enabled,
        staleTime: 0,
      })),
    ],
    combine,
  });

  const queryClient = useQueryClient();

  const invalidate = useCallback(() => {
    return Promise.all([
      ...invocationQueries.map((invocationQuery) =>
        queryClient.invalidateQueries({
          queryKey: invocationQuery.queryKey,
        }),
      ),
    ]);
  }, [invocationQueries, queryClient]);

  return {
    ...results,
    refetch: () => {
      return Promise.all([
        ...invocationQueries.map((invocationQuery) =>
          queryClient.refetchQueries({
            queryKey: invocationQuery.queryKey,
          }),
        ),
      ]);
    },
    invalidate,
  };
}

export function useGetVirtualObjectQueue(
  serviceName: string,
  key: string,
  invocationId?: string,
  scope?: string,
  options?: HookQueryOptions<
    '/query/virtualObjects/{name}/keys/{key}/queue',
    'get'
  >,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = adminApi(
    'query',
    '/query/virtualObjects/{name}/keys/{key}/queue',
    'get',
    {
      baseUrl,
      parameters: {
        path: { key, name: serviceName },
        query: { invocationId, scope },
      },
    },
  );

  const results = useQuery({
    ...queryOptions,
    ...options,
    enabled: options?.enabled !== false && enabled,
  });

  return {
    ...results,
    queryKey: queryOptions.queryKey,
  };
}

export function useGetVirtualObjectState(
  serviceName: string,
  key: string,
  scope?: string,
  serviceType?: 'virtual_object' | 'workflow' | 'service',
  options?: HookQueryOptions<'/query/services/{name}/keys/{key}/state', 'get'>,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions =
    scope !== undefined
      ? adminApi(
          'query',
          '/query/services/{name}/scopes/{scope}/keys/{key}/state',
          'get',
          {
            baseUrl,
            parameters: { path: { name: serviceName, scope, key } },
          },
        )
      : adminApi('query', '/query/services/{name}/keys/{key}/state', 'get', {
          baseUrl,
          parameters: {
            path: { key, name: serviceName },
            ...(serviceType ? { query: { serviceType } } : {}),
          },
        });

  const results = useQuery({
    ...queryOptions,
    ...options,
    enabled: options?.enabled !== false && enabled,
  });

  return {
    ...results,
    queryKey: queryOptions.queryKey,
  };
}

export function useGetVirtualObjectStateInterface(
  serviceName: string,
  serviceKey: string[],
  scope?: string,
  serviceType?: 'virtual_object' | 'workflow' | 'service',
  options?: HookQueryOptions<'/query/services/{name}/state/keys', 'get'>,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = adminApi(
    'query',
    '/query/services/{name}/state/keys',
    'get',
    {
      baseUrl,
      parameters: {
        path: { name: serviceName },
        query: {
          serviceKey,
          ...(scope !== undefined ? { scope } : {}),
          ...(serviceType ? { serviceType } : {}),
        },
      },
    },
  );

  const results = useQuery({
    ...queryOptions,
    ...options,
    enabled: options?.enabled !== false && enabled,
  });

  return {
    ...results,
    queryKey: queryOptions.queryKey,
  };
}

export function useQueryVirtualObjectState(
  serviceName: string,
  args: { systemFilters?: FilterItem[]; stateFilter?: FilterItem },
  serviceType?: 'virtual_object' | 'workflow' | 'service',
  options?: HookQueryOptions<'/query/services/{name}/state/query', 'post'>,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = adminApi(
    'query',
    '/query/services/{name}/state/query',
    'post',
    {
      baseUrl,
      parameters: {
        path: { name: serviceName },
        ...(serviceType ? { query: { serviceType } } : {}),
      },
      body: args,
      resolvedPath: serviceType
        ? `/query/services/${serviceName}/state/query?serviceType=${serviceType}`
        : `/query/services/${serviceName}/state/query`,
    },
  );
  const results = useQuery({
    ...queryOptions,
    ...options,
    enabled: options?.enabled !== false && enabled,
  });

  return {
    ...results,
    queryKey: queryOptions.queryKey,
    isPending: results.isPending || !enabled,
  };
}

export function useListVirtualObjectState(
  serviceName: string,
  args: { keys: string[] } | { items: { key: string; scope?: string }[] },
  serviceType?: 'virtual_object' | 'workflow' | 'service',
  options?: HookQueryOptions<'/query/services/{name}/state', 'post'>,
) {
  const enabled = useAPIStatus();
  const baseUrl = useAdminBaseUrl();
  const queryOptions = adminApi(
    'query',
    '/query/services/{name}/state',
    'post',
    {
      baseUrl,
      parameters: {
        path: { name: serviceName },
        ...(serviceType ? { query: { serviceType } } : {}),
      },
      body: args,
      resolvedPath: serviceType
        ? `/query/services/${serviceName}/state?serviceType=${serviceType}`
        : `/query/services/${serviceName}/state`,
    },
  );

  const length = 'keys' in args ? args.keys.length : args.items.length;

  const results = useQuery({
    ...queryOptions,
    ...options,
    enabled: length > 0 && options?.enabled !== false && enabled,
  });

  return {
    ...results,
    queryKey: queryOptions.queryKey,
  };
}

export function useKillInvocation(
  invocation_id: string,
  options?: HookMutationOptions<'/invocations/{invocation_id}/kill', 'patch'>,
) {
  const baseUrl = useAdminBaseUrl();
  const queryCLient = useQueryClient();

  return useMutation({
    ...adminApi('mutate', '/invocations/{invocation_id}/kill', 'patch', {
      baseUrl,
      resolvedPath: `/invocations/${invocation_id}/kill`,
    }),
    ...options,
    onSuccess(data, variables, context, meta) {
      options?.onSuccess?.(data, variables, context, meta);

      queryCLient.invalidateQueries({
        queryKey: adminApi(
          'query',
          '/query/v2/invocations/{invocationId}',
          'get',
          {
            baseUrl,
            parameters: {
              path: {
                invocationId: String(variables.parameters?.path.invocation_id),
              },
              query: { journal: true },
            },
          },
        ).queryKey,
      });
      queryCLient.invalidateQueries({
        predicate(query) {
          const queryKey = query.queryKey;
          if (
            Array.isArray(queryKey) &&
            queryKey.at(0) === '/query/invocations'
          ) {
            return true;
          }
          return false;
        },
      });
    },
  });
}

export function useCancelInvocation(
  invocation_id: string,
  options?: HookMutationOptions<'/invocations/{invocation_id}/cancel', 'patch'>,
) {
  const baseUrl = useAdminBaseUrl();
  const queryCLient = useQueryClient();

  return useMutation({
    ...adminApi('mutate', '/invocations/{invocation_id}/cancel', 'patch', {
      baseUrl,
      resolvedPath: `/invocations/${invocation_id}/cancel`,
    }),
    ...options,
    onSuccess(data, variables, context, meta) {
      options?.onSuccess?.(data, variables, context, meta);

      queryCLient.invalidateQueries({
        queryKey: adminApi(
          'query',
          '/query/v2/invocations/{invocationId}',
          'get',
          {
            baseUrl,
            parameters: {
              path: {
                invocationId: String(variables.parameters?.path.invocation_id),
              },
              query: { journal: true },
            },
          },
        ).queryKey,
      });
      queryCLient.invalidateQueries({
        predicate(query) {
          const queryKey = query.queryKey;
          if (
            Array.isArray(queryKey) &&
            queryKey.at(0) === '/query/invocations'
          ) {
            return true;
          }
          return false;
        },
      });
    },
  });
}

export function usePurgeInvocation(
  invocation_id: string,
  options?: HookMutationOptions<'/invocations/{invocation_id}/purge', 'patch'>,
) {
  const baseUrl = useAdminBaseUrl();
  const queryCLient = useQueryClient();

  return useMutation({
    ...adminApi('mutate', '/invocations/{invocation_id}/purge', 'patch', {
      baseUrl,
      resolvedPath: `/invocations/${invocation_id}/purge`,
    }),
    ...options,
    onSuccess(data, variables, context, meta) {
      options?.onSuccess?.(data, variables, context, meta);
      queryCLient.invalidateQueries({
        predicate(query) {
          const queryKey = query.queryKey;
          if (
            Array.isArray(queryKey) &&
            queryKey.at(0) === '/query/invocations'
          ) {
            return true;
          }
          return false;
        },
      });
    },
  });
}

export function usePauseInvocation(
  invocationId: string,
  options?: HookMutationOptions<'/invocations/{invocation_id}/pause', 'patch'>,
) {
  const baseUrl = useAdminBaseUrl();
  const queryCLient = useQueryClient();

  return useMutation({
    ...adminApi('mutate', '/invocations/{invocation_id}/pause', 'patch', {
      baseUrl,
      resolvedPath: `/invocations/${invocationId}/pause`,
    }),
    ...options,
    async onSuccess(data, variables, context, meta) {
      queryCLient.invalidateQueries({
        queryKey: adminApi(
          'query',
          '/query/v2/invocations/{invocationId}',
          'get',
          {
            baseUrl,
            parameters: {
              path: {
                invocationId: String(variables.parameters?.path.invocation_id),
              },
              query: { journal: true },
            },
          },
        ).queryKey,
      });
      queryCLient.invalidateQueries({
        predicate(query) {
          const queryKey = query.queryKey;
          if (
            Array.isArray(queryKey) &&
            queryKey.at(0) === '/query/invocations'
          ) {
            return true;
          }
          return false;
        },
      });
      options?.onSuccess?.(data, variables, context, meta);
    },
  });
}

export function useRestartInvocationAsNew(
  invocation_id: string,
  options?: HookMutationOptions<
    '/invocations/{invocation_id}/restart-as-new',
    'patch'
  >,
) {
  const baseUrl = useAdminBaseUrl();

  return useMutation({
    ...adminApi(
      'mutate',
      '/invocations/{invocation_id}/restart-as-new',
      'patch',
      {
        baseUrl,
        resolvedPath: `/invocations/${invocation_id}/restart-as-new`,
      },
    ),
    ...options,
  });
}

export function useRestartWorkflowAsNew(
  invocationId: string,
  options?: MutationOptions<
    {
      invocationId: string;
      status: string;
    },
    Error,
    {
      invocationId: string;
      workflowId: string;
    },
    unknown
  >,
) {
  const { ingressUrl, isVersionGte } = useRestateContext();
  const baseUrl = useAdminBaseUrl();
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [`/invocations/${invocationId}/restart-as-new`],
    mutationFn: async ({
      invocationId,
      workflowId,
    }: {
      invocationId: string;
      workflowId: string;
    }) => {
      const data = await queryClient.ensureQueryData(
        adminApi('query', '/query/v2/invocations/{invocationId}', 'get', {
          baseUrl,
          parameters: {
            path: { invocationId },
            query: { journal: true, includePayloads: false },
          },
        }),
      );
      const payloadData = await queryClient.ensureQueryData(
        adminApi(
          'query',
          '/query/invocations/{invocationId}/journal/{entryIndex}/payloads',
          'get',
          {
            baseUrl,
            parameters: { path: { invocationId, entryIndex: 0 } },
          },
        ),
      );
      const inputEntry = data?.journal?.entries?.find(
        (entry) => entry.type === 'Input',
      ) as Extract<JournalEntryV2, { type?: 'Input'; category?: 'command' }>;
      if (!inputEntry || !payloadData) {
        throw new RestateError(
          'The invocation cannot be restarted because the input is not available. In order to restart an invocation, the journal must be available in order to read the input again. Journal can be retained after completion by enabling journal retention.',
        );
      }
      const body = payloadData.parameters;
      const headers = payloadData.headers;

      const scope = data?.scope;
      const sendUrl = isVersionGte?.('1.7.0')
        ? scope
          ? `${ingressUrl.replace(/\/$/, '')}/restate/scope/${scope}/send/${data?.target_service_name}/${workflowId}/${data?.target_handler_name}`
          : `${ingressUrl.replace(/\/$/, '')}/restate/send/${data?.target_service_name}/${workflowId}/${data?.target_handler_name}`
        : `${ingressUrl.replace(/\/$/, '')}/${data?.target_service_name}/${workflowId}/${data?.target_handler_name}/send`;

      return fetch(sendUrl, {
        credentials: 'include',
        method: 'POST',
        body: body ? base64ToUint8Array(body) : undefined,
        headers: headers
          ?.filter(
            ({ key }) =>
              !['x-forwarded-for', 'x-forwarded-host'].includes(key) &&
              !key.startsWith('x-restate-'),
          )
          .reduce(
            (acc, { key, value }) => ({ ...acc, [key]: value }),
            {} as Record<string, string>,
          ),
      }).then(async (res) => {
        if (res.ok) {
          return (await res.json()) as {
            invocationId: string;
            status: string;
          };
        } else {
          throw await res.json();
        }
      });
    },
    ...options,
  });
}

export function useResumeInvocation(
  invocationId: string,
  options?: HookMutationOptions<'/invocations/{invocation_id}/resume', 'patch'>,
) {
  const baseUrl = useAdminBaseUrl();
  const queryCLient = useQueryClient();

  return useMutation({
    ...adminApi('mutate', '/invocations/{invocation_id}/resume', 'patch', {
      baseUrl,
      resolvedPath: `/invocations/${invocationId}/resume`,
    }),
    ...options,
    onSuccess(data, variables, context, meta) {
      options?.onSuccess?.(data, variables, context, meta);

      queryCLient.invalidateQueries({
        queryKey: adminApi(
          'query',
          '/query/v2/invocations/{invocationId}',
          'get',
          {
            baseUrl,
            parameters: {
              path: {
                invocationId: String(variables.parameters?.path.invocation_id),
              },
              query: { journal: true },
            },
          },
        ).queryKey,
      });
      queryCLient.invalidateQueries({
        predicate(query) {
          const queryKey = query.queryKey;
          if (
            Array.isArray(queryKey) &&
            queryKey.at(0) === '/query/invocations'
          ) {
            return true;
          }
          return false;
        },
      });
    },
  });
}

export function convertStateToObject<T>(state: { name: string; value: T }[]) {
  return state.reduce(
    (p, c) => ({ ...p, [c.name]: c.value }),
    {} as Record<string, T>,
  );
}
