const MIN_OVERVIEW_REFETCH_INTERVAL = 10_000;
const MAX_OVERVIEW_REFETCH_INTERVAL = 60_000;
const OVERVIEW_REFETCH_DURATION_MULTIPLIER = 10;

export function getOverviewRefetchInterval(summaryFetchDuration: number) {
  return Math.min(
    MAX_OVERVIEW_REFETCH_INTERVAL,
    Math.max(
      MIN_OVERVIEW_REFETCH_INTERVAL,
      summaryFetchDuration * OVERVIEW_REFETCH_DURATION_MULTIPLIER,
    ),
  );
}

export const INITIAL_OVERVIEW_REFETCH_INTERVAL = MIN_OVERVIEW_REFETCH_INTERVAL;
