/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/cluster-health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Cluster health
     * @description Get the cluster health.
     */
    get: operations['cluster_health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/deployments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List deployments
     * @description List all registered deployments.
     */
    get: operations['list_deployments'];
    put?: never;
    /**
     * Create deployment
     * @description Create deployment. Restate will invoke the endpoint to gather additional information required for registration, such as the services exposed by the deployment. If the deployment is already registered, this method will fail unless `force` is set to `true`.
     */
    post: operations['create_deployment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/deployments/{deployment}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get deployment
     * @description Get deployment metadata
     */
    get: operations['get_deployment'];
    /**
     * Update deployment
     * @description Update deployment. Invokes the endpoint and replaces the existing deployment metadata with the discovered information. This is a dangerous operation that should be used only when there are failing invocations on the deployment that cannot be resolved any other way. Sense checks are applied to test that the new deployment is sufficiently similar to the old one.
     */
    put: operations['update_deployment'];
    post?: never;
    /**
     * Delete deployment
     * @description Delete deployment. Currently it's supported to remove a deployment only using the force flag
     */
    delete: operations['delete_deployment'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Check REST API Health.
     */
    get: operations['health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/invocations/{invocation_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete an invocation
     * @description Delete the given invocation. By default, an invocation is terminated by gracefully cancelling it. This ensures virtual object state consistency. Alternatively, an invocation can be killed which does not guarantee consistency for virtual object instance state, in-flight invocations to other services, etc. A stored completed invocation can also be purged
     */
    delete: operations['delete_invocation'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/openapi': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** OpenAPI specification */
    get: operations['openapi_spec'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/services': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List services
     * @description List all registered services.
     */
    get: operations['list_services'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/services/{service}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get service
     * @description Get a registered service.
     */
    get: operations['get_service'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Modify a service
     * @description Modify a registered service.
     */
    patch: operations['modify_service'];
    trace?: never;
  };
  '/services/{service}/handlers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List service handlers
     * @description List all the handlers of the given service.
     */
    get: operations['list_service_handlers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/services/{service}/handlers/{handler}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get service handler
     * @description Get the handler of a service
     */
    get: operations['get_service_handler'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/services/{service}/openapi': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get service OpenAPI
     * @description Get the service OpenAPI 3.1 contract.
     */
    get: operations['get_service_openapi'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/services/{service}/state': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Modify a service state
     * @description Modify service state
     */
    post: operations['modify_service_state'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/subscriptions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List subscriptions
     * @description List all subscriptions.
     */
    get: operations['list_subscriptions'];
    put?: never;
    /**
     * Create subscription
     * @description Create subscription.
     */
    post: operations['create_subscription'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/subscriptions/{subscription}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get subscription
     * @description Get subscription
     */
    get: operations['get_subscription'];
    put?: never;
    post?: never;
    /**
     * Delete subscription
     * @description Delete subscription.
     */
    delete: operations['delete_subscription'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/version': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Admin version information
     * @description Obtain admin version information.
     */
    get: operations['version'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/query': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Query journal
     * @description Query journal
     */
    post: operations['query'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/query/invocations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * List invocations
     * @description List invocations
     */
    post: operations['list_invocations'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/query/invocations/{invocationId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get invocation
     * @description Get invocation
     */
    get: operations['get_invocation'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/query/invocations/{invocationId}/journal': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get invocation journal
     * @description Get invocation journal
     */
    get: operations['get_invocation_journal'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/query/virtualObjects/{name}/keys/{key}/queue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Virtual Object inbox inbox for a key
     * @description Get Virtual Object inbox inbox for a key
     */
    get: operations['get_inbox'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/query/services/{name}/state/keys': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get state keys
     * @description Get state keys
     */
    get: operations['get_state_keys'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/query/services/{name}/state': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * List virtual object state
     * @description List virtual object state
     */
    post: operations['list_virtual_object_state'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/query/services/{name}/keys/{key}/state': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get state keys
     * @description Get state keys
     */
    get: operations['get_state'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/query/services/{name}/state/query': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Query virtual object state
     * @description Query virtual object state
     */
    post: operations['query_virtual_object_state'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ClusterHealthResponse: {
      /** @description Cluster name */
      cluster_name: string;
      /** @description Embedded metadata cluster health if it was enabled */
      metadata_cluster_health?:
        | components['schemas']['EmbeddedMetadataClusterHealth']
        | null;
    };
    EmbeddedMetadataClusterHealth: {
      /** @description Current members of the embedded metadata cluster */
      members: number[];
    };
    /**
     * Error description response
     * @description Error details of the response
     */
    ErrorDescriptionResponse: {
      message: string;
      /**
       * Restate code
       * @description Restate error code describing this error
       */
      restate_code?: string | null;
    };
    ListDeploymentsResponse: {
      deployments: components['schemas']['DeploymentResponse'][];
    };
    DeploymentResponse:
      | {
          id: components['schemas']['String'];
          /**
           * Services
           * @description List of services exposed by this deployment.
           */
          services: components['schemas']['ServiceNameRevPair'][];
          uri: string;
          protocol_type: components['schemas']['ProtocolType'];
          http_version: string;
          additional_headers?: {
            [key: string]: string;
          };
          created_at: string;
          /** Format: int32 */
          min_protocol_version: number;
          /** Format: int32 */
          max_protocol_version: number;
        }
      | {
          id: components['schemas']['String'];
          /**
           * Services
           * @description List of services exposed by this deployment.
           */
          services: components['schemas']['ServiceNameRevPair'][];
          arn: components['schemas']['LambdaARN'];
          assume_role_arn?: string | null;
          additional_headers?: {
            [key: string]: string;
          };
          created_at: string;
          /** Format: int32 */
          min_protocol_version: number;
          /** Format: int32 */
          max_protocol_version: number;
        };
    String: string;
    ServiceNameRevPair: {
      name: string;
      /** Format: uint32 */
      revision: number;
    };
    /** @enum {string} */
    ProtocolType: 'RequestResponse' | 'BidiStream';
    /** Format: arn */
    LambdaARN: string;
    RegisterDeploymentRequest:
      | {
          /**
           * Uri
           * @description Uri to use to discover/invoke the http deployment.
           */
          uri: string;
          /**
           * Additional headers
           * @description Additional headers added to the discover/invoke requests to the deployment.
           */
          additional_headers?: {
            [key: string]: string;
          } | null;
          /**
           * Use http1.1
           * @description If `true`, discovery will be attempted using a client that defaults to HTTP1.1 instead of a prior-knowledge HTTP2 client. HTTP2 may still be used for TLS servers that advertise HTTP2 support via ALPN. HTTP1.1 deployments will only work in request-response mode.
           * @default false
           */
          use_http_11: boolean;
          /**
           * Force
           * @description If `true`, it will override, if existing, any deployment using the same `uri`. Beware that this can lead in-flight invocations to an unrecoverable error state.
           *
           *     By default, this is `true` but it might change in future to `false`.
           *
           *     See the [versioning documentation](https://docs.restate.dev/operate/versioning) for more information.
           * @default true
           */
          force: boolean;
          /**
           * Dry-run mode
           * @description If `true`, discovery will run but the deployment will not be registered. This is useful to see the impact of a new deployment before registering it.
           * @default false
           */
          dry_run: boolean;
        }
      | {
          /**
           * ARN
           * @description ARN to use to discover/invoke the lambda deployment.
           */
          arn: string;
          /**
           * Assume role ARN
           * @description Optional ARN of a role to assume when invoking the addressed Lambda, to support role chaining
           */
          assume_role_arn?: string | null;
          /**
           * Additional headers
           * @description Additional headers added to the discover/invoke requests to the deployment.
           */
          additional_headers?: {
            [key: string]: string;
          } | null;
          /**
           * Force
           * @description If `true`, it will override, if existing, any deployment using the same `uri`. Beware that this can lead in-flight invocations to an unrecoverable error state.
           *
           *     By default, this is `true` but it might change in future to `false`.
           *
           *     See the [versioning documentation](https://docs.restate.dev/operate/versioning) for more information.
           * @default true
           */
          force: boolean;
          /**
           * Dry-run mode
           * @description If `true`, discovery will run but the deployment will not be registered. This is useful to see the impact of a new deployment before registering it.
           * @default false
           */
          dry_run: boolean;
        };
    RegisterDeploymentResponse: {
      id: components['schemas']['String'];
      services: components['schemas']['ServiceMetadata'][];
    };
    ServiceMetadata: {
      /**
       * Name
       * @description Fully qualified name of the service
       */
      name: string;
      handlers: components['schemas']['HandlerMetadata'][];
      ty: components['schemas']['ServiceType'];
      /**
       * Documentation
       * @description Documentation of the service, as propagated by the SDKs.
       */
      documentation?: string | null;
      /**
       * Metadata
       * @description Additional service metadata, as propagated by the SDKs.
       */
      metadata?: {
        [key: string]: string;
      };
      /**
       * Deployment Id
       * @description Deployment exposing the latest revision of the service.
       */
      deployment_id: string;
      /**
       * Revision
       * Format: uint32
       * @description Latest revision of the service.
       */
      revision: number;
      /**
       * Public
       * @description If true, the service can be invoked through the ingress. If false, the service can be invoked only from another Restate service.
       */
      public: boolean;
      /**
       * Idempotency retention
       * @description The retention duration of idempotent requests for this service.
       */
      idempotency_retention: string;
      /**
       * Workflow completion retention
       * @description The retention duration of workflows. Only available on workflow services.
       */
      workflow_completion_retention?: string | null;
      /**
       * Inactivity timeout
       * @description This timer guards against stalled service/handler invocations. Once it expires, Restate triggers a graceful termination by asking the service invocation to suspend (which preserves intermediate progress).
       *
       *     The 'abort timeout' is used to abort the invocation, in case it doesn't react to the request to suspend.
       *
       *     Can be configured using the [`humantime`](https://docs.rs/humantime/latest/humantime/fn.parse_duration.html) format.
       *
       *     This overrides the default inactivity timeout set in invoker options.
       */
      inactivity_timeout?: string | null;
      /**
       * Abort timeout
       * @description This timer guards against stalled service/handler invocations that are supposed to terminate. The abort timeout is started after the 'inactivity timeout' has expired and the service/handler invocation has been asked to gracefully terminate. Once the timer expires, it will abort the service/handler invocation.
       *
       *     This timer potentially **interrupts** user code. If the user code needs longer to gracefully terminate, then this value needs to be set accordingly.
       *
       *     Can be configured using the [`humantime`](https://docs.rs/humantime/latest/humantime/fn.parse_duration.html) format.
       *
       *     This overrides the default abort timeout set in invoker options.
       */
      abort_timeout?: string | null;
    };
    HandlerMetadata: {
      name: string;
      ty?: components['schemas']['HandlerMetadataType'] | null;
      /**
       * Documentation
       * @description Documentation of the handler, as propagated by the SDKs.
       */
      documentation?: string | null;
      /**
       * Metadata
       * @description Additional handler metadata, as propagated by the SDKs.
       */
      metadata?: {
        [key: string]: string;
      };
      /**
       * Human readable input description
       * @description If empty, no schema was provided by the user at discovery time.
       */
      input_description: string;
      /**
       * Human readable output description
       * @description If empty, no schema was provided by the user at discovery time.
       */
      output_description: string;
      /**
       * Input JSON Schema
       * @description JSON Schema of the handler input
       */
      input_json_schema?: unknown;
      /**
       * Output JSON Schema
       * @description JSON Schema of the handler output
       */
      output_json_schema?: unknown;
    };
    /** @enum {string} */
    HandlerMetadataType: 'Exclusive' | 'Shared' | 'Workflow';
    /** @enum {string} */
    ServiceType: 'Service' | 'VirtualObject' | 'Workflow';
    DetailedDeploymentResponse:
      | {
          uri: string;
          protocol_type: components['schemas']['ProtocolType'];
          http_version: string;
          additional_headers?: {
            [key: string]: string;
          };
          created_at: string;
          /** Format: int32 */
          min_protocol_version: number;
          /** Format: int32 */
          max_protocol_version: number;
          id: components['schemas']['String'];
          /**
           * Services
           * @description List of services exposed by this deployment.
           */
          services: components['schemas']['ServiceMetadata'][];
        }
      | {
          arn: components['schemas']['LambdaARN'];
          assume_role_arn?: string | null;
          additional_headers?: {
            [key: string]: string;
          };
          created_at: string;
          /** Format: int32 */
          min_protocol_version: number;
          /** Format: int32 */
          max_protocol_version: number;
          id: components['schemas']['String'];
          /**
           * Services
           * @description List of services exposed by this deployment.
           */
          services: components['schemas']['ServiceMetadata'][];
        };
    UpdateDeploymentRequest:
      | {
          /**
           * Uri
           * @description Uri to use to discover/invoke the http deployment.
           */
          uri: string;
          /**
           * Additional headers
           * @description Additional headers added to the discover/invoke requests to the deployment.
           */
          additional_headers?: {
            [key: string]: string;
          } | null;
          /**
           * Use http1.1
           * @description If `true`, discovery will be attempted using a client that defaults to HTTP1.1 instead of a prior-knowledge HTTP2 client. HTTP2 may still be used for TLS servers that advertise HTTP2 support via ALPN. HTTP1.1 deployments will only work in request-response mode.
           * @default false
           */
          use_http_11: boolean;
          /**
           * Dry-run mode
           * @description If `true`, discovery will run but the deployment will not be registered. This is useful to see the impact of a new deployment before registering it.
           * @default false
           */
          dry_run: boolean;
        }
      | {
          /**
           * ARN
           * @description ARN to use to discover/invoke the lambda deployment.
           */
          arn: string;
          /**
           * Assume role ARN
           * @description Optional ARN of a role to assume when invoking the addressed Lambda, to support role chaining
           */
          assume_role_arn?: string | null;
          /**
           * Additional headers
           * @description Additional headers added to the discover/invoke requests to the deployment.
           */
          additional_headers?: {
            [key: string]: string;
          } | null;
          /**
           * Dry-run mode
           * @description If `true`, discovery will run but the deployment will not be registered. This is useful to see the impact of a new deployment before registering it.
           * @default false
           */
          dry_run: boolean;
        };
    /** @enum {string} */
    DeletionMode: 'Cancel' | 'Kill' | 'Purge';
    ListServicesResponse: {
      services: components['schemas']['ServiceMetadata'][];
    };
    ModifyServiceRequest: {
      /**
       * Public
       * @description If true, the service can be invoked through the ingress. If false, the service can be invoked only from another Restate service.
       * @default null
       */
      public: boolean | null;
      /**
       * Idempotency retention
       * @description Modify the retention of idempotent requests for this service.
       *
       *     Can be configured using the [`humantime`](https://docs.rs/humantime/latest/humantime/fn.parse_duration.html) format or the ISO8601.
       * @default null
       */
      idempotency_retention: string | null;
      /**
       * Workflow completion retention
       * @description Modify the retention of the workflow completion. This can be modified only for workflow services!
       *
       *     Can be configured using the [`humantime`](https://docs.rs/humantime/latest/humantime/fn.parse_duration.html) format or the ISO8601.
       * @default null
       */
      workflow_completion_retention: string | null;
      /**
       * Inactivity timeout
       * @description This timer guards against stalled service/handler invocations. Once it expires, Restate triggers a graceful termination by asking the service invocation to suspend (which preserves intermediate progress).
       *
       *     The 'abort timeout' is used to abort the invocation, in case it doesn't react to the request to suspend.
       *
       *     Can be configured using the [`humantime`](https://docs.rs/humantime/latest/humantime/fn.parse_duration.html) format or the ISO8601.
       *
       *     This overrides the default inactivity timeout set in invoker options.
       * @default null
       */
      inactivity_timeout: string | null;
      /**
       * Abort timeout
       * @description This timer guards against stalled service/handler invocations that are supposed to terminate. The abort timeout is started after the 'inactivity timeout' has expired and the service/handler invocation has been asked to gracefully terminate. Once the timer expires, it will abort the service/handler invocation.
       *
       *     This timer potentially **interrupts** user code. If the user code needs longer to gracefully terminate, then this value needs to be set accordingly.
       *
       *     Can be configured using the [`humantime`](https://docs.rs/humantime/latest/humantime/fn.parse_duration.html) format or the ISO8601.
       *
       *     This overrides the default abort timeout set in invoker options.
       * @default null
       */
      abort_timeout: string | null;
    };
    ListServiceHandlersResponse: {
      handlers: components['schemas']['HandlerMetadata'][];
    };
    ModifyServiceStateRequest: {
      /**
       * Version
       * @description If set, the latest version of the state is compared with this value and the operation will fail when the versions differ.
       */
      version?: string | null;
      /**
       * Service key
       * @description To what virtual object key to apply this change
       */
      object_key: string;
      /**
       * New State
       * @description The new state to replace the previous state with
       */
      new_state: {
        [key: string]: number[];
      };
    };
    ListSubscriptionsResponse: {
      subscriptions: components['schemas']['SubscriptionResponse'][];
    };
    SubscriptionResponse: {
      id: components['schemas']['String'];
      source: string;
      sink: string;
      options: {
        [key: string]: string;
      };
    };
    CreateSubscriptionRequest: {
      /**
       * Source
       * @description Source uri. Accepted forms:
       *
       *     * `kafka://<cluster_name>/<topic_name>`, e.g. `kafka://my-cluster/my-topic`
       */
      source: string;
      /**
       * Sink
       * @description Sink uri. Accepted forms:
       *
       *     * `service://<service_name>/<service_name>`, e.g. `service://Counter/count`
       */
      sink: string;
      /**
       * Options
       * @description Additional options to apply to the subscription.
       */
      options?: {
        [key: string]: string;
      } | null;
    };
    VersionInformation: {
      /**
       * Admin server version
       * @description Version of the admin server
       */
      version: string;
      /**
       * Min admin API version
       * Format: uint16
       * @description Minimum supported admin API version by the admin server
       */
      min_admin_api_version: number;
      /**
       * Max admin API version
       * Format: uint16
       * @description Maximum supported admin API version by the admin server
       */
      max_admin_api_version: number;
      /**
       * Ingress endpoint
       * Format: uri
       * @description Ingress endpoint that the Web UI should use to interact with.
       */
      ingress_endpoint: string;
    };
    VirtualObjectState: string[];
    ListInvocationsRequestBody: {
      filters?: components['schemas']['FilterItem'][];
    };
    ListVirtualObjectStateRequestBody: {
      filters?: components['schemas']['FilterItem'][];
    };
    FilterItem: components['schemas']['FilterBaseItem'] &
      (
        | components['schemas']['FilterNumberItem']
        | components['schemas']['FilterStringItem']
        | components['schemas']['FilterDateItem']
        | components['schemas']['FilterStringListItem']
        | components['schemas']['FilterNullItem']
      );
    FilterBaseItem: {
      /** @enum {string} */
      type: 'STRING' | 'NUMBER' | 'DATE' | 'STRING_LIST' | 'NULL';
      field: string;
    };
    FilterNumberItem: {
      /** @enum {string} */
      type: 'NUMBER';
      /** @enum {string} */
      operation:
        | 'EQUALS'
        | 'NOT_EQUALS'
        | 'GREATER_THAN'
        | 'LESS_THAN'
        | 'GREATER_THAN_OR_EQUAL'
        | 'LESS_THAN_OR_EQUAL';
      value?: number;
    };
    FilterStringItem: {
      /** @enum {string} */
      type: 'STRING';
      /** @enum {string} */
      operation: 'EQUALS' | 'NOT_EQUALS' | 'CONTAINS' | 'NOT_CONTAINS';
      value?: string;
    };
    FilterNullItem: {
      /** @enum {string} */
      type: 'NULL';
      /** @enum {string} */
      operation: 'IS' | 'IS_NOT';
    };
    FilterStringListItem: {
      /** @enum {string} */
      type: 'STRING_LIST';
      /** @enum {string} */
      operation: 'IN' | 'NOT_IN';
      value: string[];
    };
    FilterDateItem: {
      /** @enum {string} */
      type: 'DATE';
      /** @enum {string} */
      operation: 'BEFORE' | 'AFTER';
      /** Format: date-time */
      value: string;
    };
    StateInterfaceResponse: {
      keys?: {
        name: string;
      }[];
    };
    StateResponse: {
      state: {
        name: string;
        value: string;
      }[];
    };
    JournalEntry: components['schemas']['JournalBaseEntry'] &
      (
        | components['schemas']['InputJournalEntryType']
        | components['schemas']['GetStateJournalEntryType']
        | components['schemas']['SetStateJournalEntryType']
        | components['schemas']['GetStateKeysJournalEntryType']
        | components['schemas']['ClearStateJournalEntryType']
        | components['schemas']['ClearAllStateJournalEntryType']
        | components['schemas']['SleepJournalEntryType']
        | components['schemas']['GetPromiseJournalEntryType']
        | components['schemas']['PeekPromiseJournalEntryType']
        | components['schemas']['CompletePromiseJournalEntryType']
        | components['schemas']['OneWayCallJournalEntryType']
        | components['schemas']['CallJournalEntryType']
        | components['schemas']['AwakeableJournalEntryType']
        | components['schemas']['CompleteAwakeableJournalEntryType']
        | components['schemas']['RunJournalEntryType']
        | components['schemas']['CancelInvocationJournalEntryType']
        | components['schemas']['GetCallInvocationIdJournalEntryType']
        | components['schemas']['AttachInvocationJournalEntryType']
        | components['schemas']['GetInvocationOutputJournalEntryType']
        | components['schemas']['CustomJournalEntryType']
        | components['schemas']['OutputJournalEntryType']
      );
    JournalRawEntry: {
      index: number;
      /** Format: binary */
      raw?: string;
      /** Format: date-time */
      sleep_wakeup_at?: string;
      completed?: boolean;
      promise_name?: string;
      invoked_target?: string;
      invoked_id?: string;
      name?: string;
      entry_json?: string;
      /** Format: data-time */
      appended_at?: string;
      version?: number;
      /** @enum {string} */
      entry_type:
        | 'Input'
        | 'Output'
        | 'GetState'
        | 'GetEagerState'
        | 'SetState'
        | 'GetStateKeys'
        | 'GetEagerStateKeys'
        | 'ClearState'
        | 'ClearAllState'
        | 'Sleep'
        | 'GetPromise'
        | 'PeekPromise'
        | 'CompletePromise'
        | 'OneWayCall'
        | 'Call'
        | 'Awakeable'
        | 'CompleteAwakeable'
        | 'Run'
        | 'CancelInvocation'
        | 'GetCallInvocationId'
        | 'AttachInvocation'
        | 'GetInvocationOutput'
        | 'Custom';
    };
    JournalBaseEntry: {
      index: number;
      version?: number;
      command_index?: number;
      /** Format: data-time */
      start?: string;
      /** Format: data-time */
      end?: string;
      completed?: boolean;
    };
    FailureEntry: {
      message?: string;
      restate_code?: string;
    };
    InputJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      /** @enum {string} */
      entry_type?: 'Input';
      body?: string;
      headers?: {
        key: string;
        value: string;
      }[];
    };
    OutputJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      /** @enum {string} */
      entry_type?: 'Output';
      body?: string;
      failure?: components['schemas']['FailureEntry'];
    };
    GetStateJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      /** @enum {string} */
      entry_type?: 'GetState' | 'GetEagerState';
      key?: string;
      value?: string;
      completed?: boolean;
      failure?: components['schemas']['FailureEntry'];
    };
    SetStateJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      /** @enum {string} */
      entry_type?: 'SetState';
      key?: string;
      value?: string;
    };
    GetStateKeysJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      /** @enum {string} */
      entry_type?: 'GetStateKeys' | 'GetEagerStateKeys';
      completed?: boolean;
      keys?: string[];
      failure?: components['schemas']['FailureEntry'];
    };
    ClearStateJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      key?: string;
      /** @enum {string} */
      entry_type?: 'ClearState';
    };
    ClearAllStateJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      /** @enum {string} */
      entry_type?: 'ClearAllState';
    };
    SleepJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      completed?: boolean;
      failure?: components['schemas']['FailureEntry'];
      /** Format: data-time */
      sleep_wakeup_at?: string;
      /** @enum {string} */
      entry_type?: 'Sleep';
    };
    GetPromiseJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      completed?: boolean;
      /** @enum {string} */
      entry_type?: 'GetPromise';
      promise_name?: string;
      value?: string;
      failure?: components['schemas']['FailureEntry'];
    };
    PeekPromiseJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      completed?: boolean;
      /** @enum {string} */
      entry_type?: 'PeekPromise';
      promise_name?: string;
      value?: string;
      failure?: components['schemas']['FailureEntry'];
    };
    CompletePromiseJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      completed?: boolean;
      promise_name?: string;
      /** @enum {string} */
      entry_type?: 'CompletePromise';
      completion?: {
        value?: string;
        failure?: components['schemas']['FailureEntry'];
      };
      failure?: components['schemas']['FailureEntry'];
    };
    OneWayCallJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      invoked_id?: string;
      invoked_target?: string;
      key?: string;
      serviceName?: string;
      handlerName?: string;
      parameters?: string;
      headers?: {
        key: string;
        value: string;
      }[];
      /** Format: date-time */
      invokeTime?: string;
      /** @enum {string} */
      entry_type?: 'OneWayCall';
    };
    CallJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      completed?: boolean;
      invoked_id?: string;
      invoked_target?: string;
      failure?: components['schemas']['FailureEntry'];
      key?: string;
      serviceName?: string;
      handlerName?: string;
      parameters?: string;
      headers?: {
        key: string;
        value: string;
      }[];
      value?: string;
      /** @enum {string} */
      entry_type?: 'Call';
    };
    AwakeableJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      completed?: boolean;
      /** @enum {string} */
      entry_type?: 'Awakeable';
      failure?: components['schemas']['FailureEntry'];
      value?: string;
    };
    CompleteAwakeableJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      /** @enum {string} */
      entry_type?: 'CompleteAwakeable';
      failure?: components['schemas']['FailureEntry'];
      value?: string;
      id?: string;
    };
    CancelInvocationJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      /** @enum {string} */
      entry_type?: 'CancelInvocation';
    };
    GetCallInvocationIdJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      completed?: boolean;
      /** @enum {string} */
      entry_type?: 'GetCallInvocationId';
    };
    AttachInvocationJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      /** @enum {string} */
      entry_type?: 'AttachInvocation';
    };
    GetInvocationOutputJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      /** @enum {string} */
      entry_type?: 'GetInvocationOutput';
    };
    CustomJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      /** @enum {string} */
      entry_type?: 'Custom';
    };
    RunJournalEntryType: components['schemas']['JournalBaseEntry'] & {
      name: string;
      /** @enum {string} */
      entry_type?: 'Run';
      failure?: components['schemas']['FailureEntry'];
      value?: string;
    };
    InboxResponse: {
      size?: number;
      head: string;
    } & {
      [key: string]: number;
    };
    Invocation: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      modified_at: string;
      /** Format: date-time */
      scheduled_at: string;
      /** Format: date-time */
      inboxed_at?: string;
      /** Format: date-time */
      running_at?: string;
      /** Format: date-time */
      completed_at?: string;
      /** Format: date-time */
      last_start_at?: string;
      /** Format: date-time */
      next_retry_at?: string;
      id: string;
      /** @enum {string} */
      invoked_by: 'ingress' | 'service';
      /** @enum {string} */
      status:
        | 'succeeded'
        | 'failed'
        | 'cancelled'
        | 'killed'
        | 'retrying'
        | 'running'
        | 'suspended'
        | 'scheduled'
        | 'pending'
        | 'ready';
      target: string;
      target_handler_name: string;
      target_service_key?: string;
      target_service_name: string;
      /** @enum {string} */
      target_service_ty: 'service' | 'virtual_object' | 'workflow';
      /** @enum {string} */
      completion_result?: 'success' | 'failure';
      completion_failure?: string;
      invoked_by_service_name?: string;
      invoked_by_id?: string;
      invoked_by_target?: string;
      pinned_deployment_id?: string;
      trace_id?: string;
      idempotency_key?: string;
      /** Format: uint32 */
      journal_size?: number;
      /** Format: uint32 */
      pinned_service_protocol_version?: number;
      /** Format: uint32 */
      journal_commands_size?: number;
      /** Format: uint64 */
      retry_count?: number;
      /** Format: uint64 */
      last_failure_related_entry_index?: number;
      last_failure_related_entry_name?: string;
      last_failure_related_entry_type?: string;
      /** Format: uint64 */
      last_failure_related_command_index?: number;
      last_failure_related_command_name?: string;
      last_failure_related_command_type?: string;
      last_attempt_deployment_id?: string;
      last_attempt_server?: string;
      last_failure?: string;
      last_failure_error_code?: string;
    };
    RawInvocation: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      modified_at: string;
      /** Format: date-time */
      scheduled_at: string;
      /** Format: date-time */
      inboxed_at?: string;
      /** Format: date-time */
      running_at?: string;
      /** Format: date-time */
      completed_at?: string;
      /** Format: date-time */
      last_start_at?: string;
      /** Format: date-time */
      next_retry_at?: string;
      id: string;
      /** @enum {string} */
      invoked_by: 'ingress' | 'service';
      /** @enum {string} */
      status:
        | 'pending'
        | 'scheduled'
        | 'ready'
        | 'running'
        | 'backing-off'
        | 'suspended'
        | 'completed';
      target: string;
      target_handler_name: string;
      target_service_key?: string;
      target_service_name: string;
      /** @enum {string} */
      target_service_ty: 'service' | 'virtual_object' | 'workflow';
      /** @enum {string} */
      completion_result?: 'success' | 'failure';
      completion_failure?: string;
      invoked_by_service_name?: string;
      invoked_by_id?: string;
      invoked_by_target?: string;
      pinned_deployment_id?: string;
      trace_id?: string;
      idempotency_key?: string;
      /** Format: uint32 */
      journal_size?: number;
      /** Format: uint32 */
      pinned_service_protocol_version?: number;
      /** Format: uint32 */
      journal_commands_size?: number;
      /** Format: uint64 */
      retry_count?: number;
      /** Format: uint64 */
      last_failure_related_command_index?: number;
      last_failure_related_command_name?: string;
      last_failure_related_command_type?: string;
      /** Format: uint64 */
      last_failure_related_entry_index?: number;
      last_failure_related_entry_name?: string;
      last_failure_related_entry_type?: string;
      last_attempt_deployment_id?: string;
      last_attempt_server?: string;
      last_failure?: string;
      last_failure_error_code?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  cluster_health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ClusterHealthResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  list_deployments: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListDeploymentsResponse'];
        };
      };
    };
  };
  create_deployment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterDeploymentRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RegisterDeploymentResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  get_deployment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Deployment identifier */
        deployment: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DetailedDeploymentResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  update_deployment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Deployment identifier */
        deployment: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateDeploymentRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DetailedDeploymentResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  delete_deployment: {
    parameters: {
      query?: {
        /** @description If true, the deployment will be forcefully deleted. This might break in-flight invocations, use with caution. */
        force?: boolean;
      };
      header?: never;
      path: {
        /** @description Deployment identifier */
        deployment: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      /** @description Not implemented. Only using the force flag is supported at the moment. */
      501: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_invocation: {
    parameters: {
      query?: {
        /** @description If cancel, it will gracefully terminate the invocation. If kill, it will terminate the invocation with a hard stop. If purge, it will only cleanup the response for completed invocations, and leave unaffected an in-flight invocation. */
        mode?: components['schemas']['DeletionMode'];
      };
      header?: never;
      path: {
        /** @description Invocation identifier. */
        invocation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  openapi_spec: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  list_services: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListServicesResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  get_service: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Fully qualified service name. */
        service: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ServiceMetadata'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  modify_service: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Fully qualified service name. */
        service: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ModifyServiceRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ServiceMetadata'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  list_service_handlers: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Fully qualified service name. */
        service: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListServiceHandlersResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  get_service_handler: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Fully qualified service name. */
        service: string;
        /** @description Handler name. */
        handler: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlerMetadata'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  get_service_openapi: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Fully qualified service name. */
        service: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OpenAPI 3.1 of the service */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  modify_service_state: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Fully qualified service name. */
        service: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ModifyServiceStateRequest'];
      };
    };
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  list_subscriptions: {
    parameters: {
      query?: {
        /** @description Filter by the exact specified sink. */
        sink?: string;
        /** @description Filter by the exact specified source. */
        source?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListSubscriptionsResponse'];
        };
      };
    };
  };
  create_subscription: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSubscriptionRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SubscriptionResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  get_subscription: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Subscription identifier */
        subscription: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SubscriptionResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  delete_subscription: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Subscription identifier */
        subscription: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  version: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VersionInformation'];
        };
      };
    };
  };
  query: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          query: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            rows?: {
              [key: string]: string;
            }[];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  list_invocations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ListInvocationsRequestBody'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            rows: components['schemas']['Invocation'][];
            total_count: number;
            limit?: number;
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  get_invocation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Invocation id */
        invocationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Invocation'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  get_invocation_journal: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Invocation id */
        invocationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            entries: components['schemas']['JournalEntry'][];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  get_inbox: {
    parameters: {
      query?: {
        /** @description Invocation id */
        invocationId?: string;
      };
      header?: never;
      path: {
        /** @description service name */
        name: string;
        /** @description key */
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InboxResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  get_state_keys: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description service name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StateInterfaceResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  list_virtual_object_state: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description service name */
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          keys: string[];
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            objects: (components['schemas']['StateResponse'] & {
              key: string;
            })[];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  get_state: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description service name */
        name: string;
        /** @description key */
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': WithRequired<
            components['schemas']['StateResponse'],
            'state'
          > & {
            version?: string;
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
  query_virtual_object_state: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description service name */
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ListVirtualObjectStateRequestBody'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            keys: string[];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDescriptionResponse'];
        };
      };
    };
  };
}
type WithRequired<T, K extends keyof T> = T & {
  [P in K]-?: T[P];
};
