import type { components } from './index'; // generated by openapi-typescript

export type Deployment =
  components['schemas']['ListDeploymentsResponse']['deployments'][number];
export type DetailedDeployment =
  components['schemas']['DetailedDeploymentResponse'];
