// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
// eslint-disable-next-line @typescript-eslint/no-empty-interface
interface Env {}
