import type { components } from './index'; // generated by openapi-typescript

export type Deployment =
  components['schemas']['ListDeploymentsResponse']['deployments'][number];
export type DetailedDeployment =
  components['schemas']['DetailedDeploymentResponse'];
export type Revision = components['schemas']['ServiceMetadata']['revision'];
export type Service = components['schemas']['ServiceMetadata'];
export type Handler = components['schemas']['HandlerMetadata'];

export type InvocationComputedStatus2 =
  components['schemas']['InvocationStatus'];

export type RawInvocation = components['schemas']['RawInvocation'];
export type JournalEntry = components['schemas']['JournalEntry'];
export type JournalEntryV2 = components['schemas']['JournalEntryV2'];
export type JournalRawEntry = components['schemas']['JournalRawEntry'];
export type InputJournalEntryType =
  components['schemas']['InputJournalEntryType'];
export type GetStateJournalEntryType =
  components['schemas']['GetStateJournalEntryType'];
export type SetStateJournalEntryType =
  components['schemas']['SetStateJournalEntryType'];
export type GetStateKeysJournalEntryType =
  components['schemas']['GetStateKeysJournalEntryType'];
export type ClearStateJournalEntryType =
  components['schemas']['ClearStateJournalEntryType'];
export type ClearAllStateJournalEntryType =
  components['schemas']['ClearAllStateJournalEntryType'];
export type SleepJournalEntryType =
  components['schemas']['SleepJournalEntryType'];
export type GetPromiseJournalEntryType =
  components['schemas']['GetPromiseJournalEntryType'];
export type PeekPromiseJournalEntryType =
  components['schemas']['PeekPromiseJournalEntryType'];
export type CompletePromiseJournalEntryType =
  components['schemas']['CompletePromiseJournalEntryType'];
export type OneWayCallJournalEntryType =
  components['schemas']['OneWayCallJournalEntryType'];
export type CallJournalEntryType =
  components['schemas']['CallJournalEntryType'];
export type AwakeableJournalEntryType =
  components['schemas']['AwakeableJournalEntryType'];
export type CompleteAwakeableJournalEntryType =
  components['schemas']['CompleteAwakeableJournalEntryType'];
export type RunJournalEntryType = components['schemas']['RunJournalEntryType'];
export type CancelInvocationJournalEntryType =
  components['schemas']['CancelInvocationJournalEntryType'];
export type GetCallInvocationIdJournalEntryType =
  components['schemas']['GetCallInvocationIdJournalEntryType'];
export type AttachInvocationJournalEntryType =
  components['schemas']['AttachInvocationJournalEntryType'];
export type GetInvocationOutputJournalEntryType =
  components['schemas']['GetInvocationOutputJournalEntryType'];
export type CustomJournalEntryType =
  components['schemas']['CustomJournalEntryType'];
export type OutputJournalEntryType =
  components['schemas']['OutputJournalEntryType'];
export type CancelSignalJournalEntryType =
  components['schemas']['CancelSignalJournalEntryType'];
export type EntryType = Exclude<JournalEntry['entry_type'], undefined>;
export type Invocation = components['schemas']['Invocation'];
export type InvocationStatus = components['schemas']['InvocationStatus'];
export type InvocationSummaryStage =
  components['schemas']['InvocationSummaryStageV2'];
export type InvocationFuture = components['schemas']['InvocationFuture'];
export type ServiceName = Service['name'];
export type DeploymentId = Deployment['id'];
export type ServiceType = Service['ty'];
export type FilterItem = components['schemas']['FilterItem'];
export type FilterDateItem = components['schemas']['FilterDateItem'];
export type FilterNumberItem = components['schemas']['FilterNumberItem'];
export type FilterNullItem = components['schemas']['FilterNullItem'];
export type FilterStringListItem =
  components['schemas']['FilterStringListItem'];
export type FilterStringItem = components['schemas']['FilterStringItem'];
export type StateResponse = components['schemas']['StateResponse'];
export type BatchInvocationsRequestBody =
  components['schemas']['BatchInvocationsRequestBody'];
export type BatchResumeInvocationsRequestBody =
  components['schemas']['BatchResumeInvocationsRequestBody'];
export type BatchInvocationsResponse =
  components['schemas']['BatchInvocationsResponse'];
export type BatchOperationResult =
  components['schemas']['BatchOperationResult'];
export type SortInvocations = Exclude<
  components['schemas']['ListInvocationsRequestBody']['sort'],
  undefined
>;
export type JournalEntryPayloads =
  components['schemas']['JournalEntryPayloads'];
export type FailureEntry = components['schemas']['FailureEntry'];

// Virtual-queue snapshot (rendered as "Flow" in the UI; kept in vqueue terms
// everywhere in code).
export type InvocationVqueue =
  components['schemas']['InvocationVqueueResponse'];
export type VqueueGateDuration = components['schemas']['VqueueGateDuration'];

export type HTTPDeployment = Exclude<Deployment, { arn: string }>;
export type LambdaDeployment = Exclude<Deployment, { uri: string }>;
export type DeploymentType = 'uri' | 'arn';

export const INVOCATION_STATUS_DEFINITIONS = [
  { key: 'scheduled', label: 'Scheduled', stage: 'inbox' },
  { key: 'pending', label: 'Pending', stage: 'inbox' },
  { key: 'ready', label: 'Ready', stage: 'inbox' },
  { key: 'yielded', label: 'Yielded', stage: 'inbox' },
  { key: 'backing-off', label: 'Backing off', stage: 'inbox' },
  { key: 'running', label: 'Running', stage: 'running' },
  { key: 'suspended', label: 'Suspended', stage: 'suspended' },
  { key: 'paused', label: 'Paused', stage: 'paused' },
  { key: 'succeeded', label: 'Succeeded', stage: 'finished' },
  { key: 'failed', label: 'Failed', stage: 'finished' },
  { key: 'cancelled', label: 'Cancelled', stage: 'finished' },
  { key: 'killed', label: 'Killed', stage: 'finished' },
] as const satisfies readonly {
  key: InvocationStatus;
  label: string;
  stage: InvocationSummaryStage;
}[];

export const INVOCATION_SUMMARY_STAGES = [
  'inbox',
  'running',
  'suspended',
  'paused',
  'finished',
] as const satisfies readonly InvocationSummaryStage[];

export const NOT_COMPLETED_INVOCATION_STAGES = INVOCATION_SUMMARY_STAGES.filter(
  (stage) => stage !== 'finished',
);

export const INVOCATION_STATUSES = INVOCATION_STATUS_DEFINITIONS.map(
  ({ key }) => key,
);

export const INBOX_INVOCATION_STATUSES = INVOCATION_STATUS_DEFINITIONS.filter(
  ({ stage }) => stage === 'inbox',
).map(({ key }) => key);

export const TERMINAL_INVOCATION_STATUSES =
  INVOCATION_STATUS_DEFINITIONS.filter(({ stage }) => stage === 'finished').map(
    ({ key }) => key,
  );

export function getInvocationStatusesForStage(stage: InvocationSummaryStage) {
  return INVOCATION_STATUS_DEFINITIONS.filter(
    (definition) => definition.stage === stage,
  ).map(({ key }) => key);
}

export function getInvocationStatusLabel(status: string) {
  return INVOCATION_STATUS_DEFINITIONS.find(({ key }) => key === status)?.label;
}
export function isHttpDeployment(
  deployment: Deployment,
): deployment is HTTPDeployment {
  return 'uri' in deployment;
}
export function isLambdaDeployment(
  deployment: Deployment,
): deployment is LambdaDeployment {
  return 'arn' in deployment;
}
export function getEndpoint(deployment?: Deployment) {
  if (!deployment) {
    return undefined;
  }
  if (isHttpDeployment(deployment)) {
    return deployment.uri;
  } else {
    return deployment.arn;
  }
}
export function getProtocolType(deployment?: Deployment) {
  if (!deployment) {
    return undefined;
  }
  if (isHttpDeployment(deployment)) {
    return deployment.protocol_type;
  }
  return 'RequestResponse';
}
