import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line @nx/enforce-module-boundaries
import * as build from '../../../dist/apps/cloud/server';

export const onRequest = createPagesFunctionHandler({ build });
