on:
  push:
    branches:
      - '**'
      - '!main'
      - '!dev'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    env:
      RESTATE_AUTH_URL: 'https://auth-dev.restate.cloud'
      RESTATE_AUTH_CLIENT_ID: '1v1rkegmilgjlphium3ksgurek'
      RESTATE_CLOUD_API_URL: 'https://api.dev.restate.cloud/cloud'
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      VERSION: ${{ github.sha }}
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: pnpm i && pnpm nx build cloud --skip-nx-cache
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: 3.60.3
          workingDirectory: apps/cloud
          command: pages deploy ../../dist/apps/cloud/client --project-name=restate-web-ui --commit-dirty=true --commit-hash=${{ github.sha }}
