on:
  push:
    tags:
      - '**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    env:
      RESTATE_AUTH_URL: 'https://auth.restate.cloud'
      RESTATE_AUTH_CLIENT_ID: '5q3dsdnrr5r400jvibd8d3k66l'
      RESTATE_CLOUD_API_URL: 'https://api.us.restate.cloud/cloud'
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: pnpm i && pnpm nx build cloud
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: 3.59.0
          workingDirectory: apps/cloud
          command: pages deploy ../../dist/apps/cloud/client --project-name=restate-web-ui --branch=dev
