on:
  push:
    tags:
      - '**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: pnpm i && pnpm nx build cloud
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'restate-web-ui'
          directory: '/dist/apps/cloud'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
