on:
  push:
    tags:
      - '**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Prod
    env:
      RESTATE_AUTH_URL: 'https://auth.restate.cloud'
      RESTATE_AUTH_REDIRECT_URL: 'https://cloud.restate.dev/auth'
      RESTATE_AUTH_CLIENT_ID: '5q3dsdnrr5r400jvibd8d3k66l'
      RESTATE_CLOUD_API_URL: 'https://api.us.restate.cloud/cloud'
      SLACK_API_URL: 'https://slack.com/api/chat.postMessage'
      VERSION: ${{ github.sha }}
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: pnpm i && pnpm nx build cloud
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: 3.60.3
          workingDirectory: apps/cloud
          command: pages deploy ../../dist/apps/cloud/client --project-name=restate-web-ui --branch=main --commit-hash=${{ github.sha }}
      - name: Cloudflare Purge Cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          PURGE_URLS: '["https://cloud.restate.dev"]'
